name: CI
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Note: we need `poetry` to run safety pre-commit hook
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
